#!/usr/bin/env php
<?php declare( strict_types = 1 );

namespace PiotrPress\WordPress\LinkChecker;

use GuzzleHttp\Client;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;

require __DIR__ . '/vendor/autoload.php';

exit( ( new SingleCommandApplication() )
    ->setName( $name = 'WordPress Link Checker' )
    ->setVersion( $version = '1.1.0' )
    ->addArgument( 'url', InputArgument::REQUIRED )
    ->addOption( 'user-agent', null, InputOption::VALUE_OPTIONAL, 'User-Agent header value', str_replace( ' ', '', $name ) . '/' . $version )
    ->addOption( 'exclude-type', null, InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY, 'Post types to exclude (by slug)' )
    ->addOption( 'exclude-post', null, InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY, 'Posts to exclude (by URL)' )
    ->setCode( function( InputInterface $input, OutputInterface $output ) use( $name, $version ) : int {
        $client = new Client( [ 'allow_redirects' => true, 'http_errors' => false, 'headers' => [ 'User-Agent' => $input->getOption( 'user-agent' ) ] ] );
        $site = new Site( $input->getArgument( 'url' ), $client );
        $check = new Check( $site->getUrl(), $client );
        foreach( $site->getPosts( $input->getOption( 'exclude-type' ), $input->getOption( 'exclude-post' ) ) as $url => $content )
            foreach( $check->getLinks( $content ) as $link => $status ) if( 400 <= $status or 0 === $status ) $output->writeln( "[ $status ] $link => $url" );
        return Command::SUCCESS;
    } )
    ->run() );